---
- hosts: all
  user: cumulus
  gather_facts: false


  tasks:
  - name: Install authorized key
    authorized_key:
      user: "{{ ansible_user }}"
      state: present
      key: "{{ lookup('file', '/home/ubuntu/.ssh/id_rsa.pub') }}"

  - name: Make sure we have a 'wheel' group
    become: true
    group:
      name: wheel
      state: present

  - name: Allow 'wheel' group to have passwordless sudo
    become: true
    lineinfile:
      dest: /etc/sudoers
      state: present
      regexp: '^%wheel'
      line: '%wheel ALL=(ALL) NOPASSWD: ALL'
      validate: visudo -cf %s

  - name: Add sudoers users to wheel group
    become: true
    user:
      name: "{{ ansible_user }}"
      groups: wheel
      append: yes